const sampleData = [
  {
    _id: "abcda",
    date: "01/01/2019",
    description: "Skyba",
    amount: 49,
    transactionType: "debit",
    category: "Gym",
    accountName: "Banking Account",
  },
  {
    _id: "abcdb",
    date: "01/01/2019",
    description: "Zoomcast",
    amount: 55,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Banking Account",
  },
  {
    _id: "abcdc",
    date: "01/01/2019",
    description: "Hack Reactor",
    amount: 418,
    transactionType: "debit",
    category: "Education",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdd",
    date: "01/01/2019",
    description: "Zoomcast",
    amount: 2.25,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Banking Account",
  },
  {
    _id: "abcde",
    date: "01/03/2019",
    description: "Bowling Lane",
    amount: 53.33,
    transactionType: "debit",
    category: "Entertainment",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdf",
    date: "01/03/2019",
    description: "Kono",
    amount: 87,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Credit Card 2",
  },
  {
    _id: "abcdg",
    date: "01/03/2019",
    description: "Verizon",
    amount: 74.35,
    transactionType: "credit",
    category: "Internet",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdh",
    date: "01/04/2019",
    description: "Viva",
    amount: 92,
    transactionType: "credit",
    category: "Restaurants",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdg",
    date: "01/04/2019",
    description: "Applebee",
    amount: 17.23,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Credit Card 2",
  },
  {
    _id: "abcdh",
    date: "01/04/2019",
    description: "Yummm",
    amount: 11.5,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdi",
    date: "01/04/2019",
    description: "Demizz",
    amount: 1626.02,
    transactionType: "credit",
    category: "Paycheck",
    accountName: "Banking Account",
  },
  {
    _id: "abcdj",
    date: "01/04/2019",
    description: "Planet Fitness",
    amount: 88,
    transactionType: "debit",
    category: "Gym",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdk",
    date: "01/05/2019",
    description: "Uber",
    amount: 289.01,
    transactionType: "debit",
    category: "Transportation",
    accountName: "Credit Card 2",
  },
  {
    _id: "abcdl",
    date: "01/05/2019",
    description: "Buzzshare",
    amount: 1679,
    transactionType: "debit",
    category: "Rent",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdm",
    date: "01/07/2019",
    description: "Yozio",
    amount: 78.3,
    transactionType: "debit",
    category: "Groceries",
    accountName: "Credit Card 1",
  },
  {
    _id: "abcdn",
    date: "01/07/2019",
    description: "Viva",
    amount: 16.22,
    transactionType: "debit",
    category: "Groceries",
    accountName: "Credit Card 2",
  },
];

export default sampleData;
