const sampleData = [
  {
    _id: "1abcda",
    date: "01/01/2019",
    description: "Skyba",
    amount: 49,
    transactionType: "debit",
    category: "Gym",
    accountName: "Banking Account",
  },
  {
    _id: "2abcdb",
    date: "01/01/2019",
    description: "Zoomcast",
    amount: 55,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Banking Account",
  },
  {
    _id: "a3bcdc",
    date: "01/01/2019",
    description: "Hack Reactor",
    amount: 418,
    transactionType: "debit",
    category: "Education",
    accountName: "Credit Card 1",
  },
  {
    _id: "ab4cdd",
    date: "01/01/2019",
    description: "Zoomcast",
    amount: 2.25,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Banking Account",
  },
  {
    _id: "abc5de",
    date: "01/03/2019",
    description: "Bowling Lane",
    amount: 53.33,
    transactionType: "debit",
    category: "Entertainment",
    accountName: "Credit Card 1",
  },
  {
    _id: "ab6cdf",
    date: "01/03/2019",
    description: "Kono",
    amount: 87,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Credit Card 2",
  },
  {
    _id: "ab7cdg",
    date: "01/03/2019",
    description: "Verizon",
    amount: 74.35,
    transactionType: "credit",
    category: "Internet",
    accountName: "Credit Card 1",
  },
  {
    _id: "ab8cdh",
    date: "01/04/2019",
    description: "Viva",
    amount: 92,
    transactionType: "credit",
    category: "Restaurants",
    accountName: "Credit Card 1",
  },
  {
    _id: "ab8cdg",
    date: "01/04/2019",
    description: "Applebee",
    amount: 17.23,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Credit Card 2",
  },
  {
    _id: "ab10cdh",
    date: "01/04/2019",
    description: "Yummm",
    amount: 11.5,
    transactionType: "debit",
    category: "Restaurants",
    accountName: "Credit Card 1",
  },
  {
    _id: "abc11di",
    date: "01/04/2019",
    description: "Demizz",
    amount: 1626.02,
    transactionType: "credit",
    category: "Paycheck",
    accountName: "Banking Account",
  },
  {
    _id: "ab12cdj",
    date: "01/04/2019",
    description: "Planet Fitness",
    amount: 88,
    transactionType: "debit",
    category: "Gym",
    accountName: "Credit Card 1",
  },
  {
    _id: "ab13cdk",
    date: "01/05/2019",
    description: "Uber",
    amount: 289.01,
    transactionType: "debit",
    category: "Transportation",
    accountName: "Credit Card 2",
  },
  {
    _id: "ab14cdl",
    date: "01/05/2019",
    description: "Buzzshare",
    amount: 1679,
    transactionType: "debit",
    category: "Rent",
    accountName: "Credit Card 1",
  },
  {
    _id: "ab15cdm",
    date: "01/07/2019",
    description: "Yozio",
    amount: 78.3,
    transactionType: "debit",
    category: "Groceries",
    accountName: "Credit Card 1",
  },
  {
    _id: "ab16cdn",
    date: "01/07/2019",
    description: "Viva",
    amount: 16.22,
    transactionType: "debit",
    category: "Groceries",
    accountName: "Credit Card 2",
  },
];

export default sampleData;
